import type * as llm from "../types/recordTypes";
export declare const createOrganization: (reqBody: llm.Organization, reqSession: any) => number;
export declare const updateOrganization: (reqBody: llm.Organization, reqSession: any) => boolean;
export declare const deleteOrganization: (organizationID: number, reqSession: any) => boolean;
export declare const restoreOrganization: (organizationID: number, reqSession: any) => boolean;
export declare const getInactiveOrganizations: (inactiveYears: number) => llm.Organization[];
export declare const getDeletedOrganizations: () => llm.Organization[];
export declare const deleteOrganizationRepresentative: (organizationID: number, representativeIndex: number) => boolean;
export declare const setDefaultOrganizationRepresentative: (organizationID: number, representativeIndex: number) => boolean;
export declare const getOrganizationRemark: (organizationID: number, remarkIndex: number, reqSession: any) => llm.OrganizationRemark;
export declare const addOrganizationRemark: (reqBody: llm.OrganizationRemark, reqSession: any) => number;
export declare const updateOrganizationRemark: (reqBody: llm.OrganizationRemark, reqSession: any) => boolean;
export declare const deleteOrganizationRemark: (organizationID: number, remarkIndex: number, reqSession: any) => boolean;
export declare const getOrganizationReminder: (organizationID: number, reminderIndex: number, reqSession: any) => llm.OrganizationReminder;
export declare const updateOrganizationReminder: (reqBody: {
    organizationID: string;
    reminderIndex: string;
    reminderTypeKey: string;
    reminderDateString?: string;
    reminderStatus: string;
    reminderNote: string;
    dismissedDateString: string;
}, reqSession: any) => boolean;
export declare const dismissOrganizationReminder: (organizationID: number, reminderIndex: number, reqSession: any) => boolean;
export declare const getOrganizationBankRecords: (organizationID: number, accountNumber: string, bankingYear: number) => llm.OrganizationBankRecord[];
export declare const getOrganizationBankRecordStats: (organizationID: number) => any[];
export declare const addOrganizationBankRecord: (reqBody: llm.OrganizationBankRecord, reqSession: any) => boolean;
export declare const updateOrganizationBankRecord: (reqBody: llm.OrganizationBankRecord, reqSession: any) => boolean;
export declare const deleteOrganizationBankRecord: (organizationID: number, recordIndex: number, reqSession: any) => boolean;
