extends:
  - "eslint:recommended"
parser: espree
parserOptions:
  ecmaVersion: 6
rules:
  # Possible Errors
  no-console: 2
  no-extra-parens: 0

  # Best Practices
  array-callback-return: 2
  block-scoped-var: 2
  complexity:
    - 1
    - 20
  consistent-return: 2
  no-alert: 1
  no-caller: 2
  no-else-return: 2
  no-empty-function: 2
  no-eval: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-extra-label: 2
  no-fallthrough: 2
  no-floating-decimal: 2
  no-implicit-coercion: 1
  no-implied-eval: 2
  no-iterator: 2
  no-labels: 2
  no-lone-blocks: 2
  no-loop-func: 2
  no-multi-spaces: 2
  no-multi-str: 2
  no-native-reassign: 2
  no-new: 2
  no-new-func: 2
  no-new-wrappers: 2
  no-octal-escape: 2
  no-param-reassign: 1
  no-proto: 2
  no-restricted-properties: 2
  no-return-assign: 2
  no-script-url: 2
  no-self-compare: 2
  no-sequences: 2
  no-throw-literal: 2
  no-unused-expressions: 2
  no-useless-call: 2
  no-useless-concat: 1
  no-useless-return: 2
  no-void: 2
  wrap-iife: 2
  yoda:
    - 2
    - never

  # Strict Mode
  strict:
    - 2
    - global

  # Variables
  no-delete-var: 2
  no-label-var: 2
  no-shadow: 2
  no-undef-init: 2
  no-undefined: 2
  no-use-before-define: 2

  # Node.js
  callback-return: 2
  global-require: 1
  no-mixed-requires: 1
  no-new-require: 2
  no-path-concat: 2
  no-process-exit: 2

  # Stylistic Issues
  array-bracket-newline: 2
  array-bracket-spacing: 2
  array-element-newline: 2
  block-spacing: 2
  brace-style: 2
  camelcase: 1
  capitalized-comments: 1
  comma-dangle: 2
  comma-spacing: 2
  comma-style: 2
  computed-property-spacing: 2
  func-call-spacing: 2
  function-paren-newline: 2
  indent: [2, 2, {
    SwitchCase: 1
    }]
  key-spacing: 2
  keyword-spacing: 2
  line-comment-position: 1
  lines-around-comment: 1
  max-depth: 1
  max-len: [1, {
    code: 120,
    tabWidth: 2,
    ignoreComments: true,
    ignoreUrls: true
    }]
  max-nested-callbacks: 2
  max-statements-per-line: 1
  multiline-comment-style: 2
  new-parens: 2
  newline-per-chained-call: 2
  no-array-constructor: 2
  no-bitwise: 2
  no-inline-comments: 1
  no-lonely-if: 2
  no-mixed-operators: 2
  no-mixed-spaces-and-tabs: 2
  no-multi-assign: 2
  no-multiple-empty-lines: 2
  no-nested-ternary: 2
  no-new-object: 2
  no-plusplus: 2
  no-spaced-func: 2
  no-trailing-spaces: 2
  no-underscore-dangle: 2
  no-unneeded-ternary: 2
  no-whitespace-before-property: 2
  object-curly-spacing: 2
  one-var:
    - 2
    - never
  one-var-declaration-per-line:
    - 2
    - always
  operator-assignment: 1
  operator-linebreak:
    - 2
    - after
  padded-blocks: 2
  quotes: 2
  semi: 2
  semi-spacing: 2
  space-before-blocks: 1
  space-in-parens: 1
  space-infix-ops: 2
  space-unary-ops: [2, {
    words: true,
    nonwords: false,
    overrides: {
      typeof: false
      }
    }]
  spaced-comment: 2
  switch-colon-spacing: 2
  template-tag-spacing: 2

  # ECMAScript 6
  arrow-body-style: 2
  arrow-spacing: 2
  no-confusing-arrow: 2
  no-duplicate-imports: 2
  no-var: 2
  prefer-const: 1
