"use strict";
const express_1 = require("express");
const permissionHandlers = require("../handlers/permissions");
const applicationSettings_1 = require("../handlers/admin-get/applicationSettings");
const doSaveApplicationSetting_1 = require("../handlers/admin-post/doSaveApplicationSetting");
const userManagement_1 = require("../handlers/admin-get/userManagement");
const doCreateUser_1 = require("../handlers/admin-post/doCreateUser");
const doUpdateUser_1 = require("../handlers/admin-post/doUpdateUser");
const doGetUserProperties_1 = require("../handlers/admin-post/doGetUserProperties");
const doUpdateUserProperty_1 = require("../handlers/admin-post/doUpdateUserProperty");
const doDeleteUser_1 = require("../handlers/admin-post/doDeleteUser");
const doResetPassword_1 = require("../handlers/admin-post/doResetPassword");
const router = express_1.Router();
router.get("/applicationSettings", permissionHandlers.adminGetHandler, applicationSettings_1.handler);
router.post("/doSaveApplicationSetting", permissionHandlers.adminPostHandler, doSaveApplicationSetting_1.handler);
router.get("/userManagement", permissionHandlers.adminGetHandler, userManagement_1.handler);
router.post("/doCreateUser", permissionHandlers.adminPostHandler, doCreateUser_1.handler);
router.post("/doUpdateUser", permissionHandlers.adminPostHandler, doUpdateUser_1.handler);
router.post("/doUpdateUserProperty", permissionHandlers.adminPostHandler, doUpdateUserProperty_1.handler);
router.post("/doResetPassword", permissionHandlers.adminPostHandler, doResetPassword_1.handler);
router.post("/doGetUserProperties", permissionHandlers.adminPostHandler, doGetUserProperties_1.handler);
router.post("/doDeleteUser", permissionHandlers.adminPostHandler, doDeleteUser_1.handler);
module.exports = router;
