"use strict";
const express_1 = require("express");
const dashboard_1 = require("../handlers/dashboard-get/dashboard");
const doChangePassword_1 = require("../handlers/dashboard-post/doChangePassword");
const doGetDefaultConfigProperties_1 = require("../handlers/dashboard-post/doGetDefaultConfigProperties");
const router = express_1.Router();
router.get("/", dashboard_1.handler);
router.post("/doChangePassword", doChangePassword_1.handler);
router.all("/doGetDefaultConfigProperties", doGetDefaultConfigProperties_1.handler);
module.exports = router;
