"use strict";
const express_1 = require("express");
const permissionHandlers = require("../handlers/permissions");
const cleanup_1 = require("../handlers/organizations-get/cleanup");
const new_1 = require("../handlers/organizations-get/new");
const view_1 = require("../handlers/organizations-get/view");
const edit_1 = require("../handlers/organizations-get/edit");
const doSearch_1 = require("../handlers/organizations-post/doSearch");
const doGetAll_1 = require("../handlers/organizations-all/doGetAll");
const doSave_1 = require("../handlers/organizations-post/doSave");
const doDelete_1 = require("../handlers/organizations-post/doDelete");
const doRestore_1 = require("../handlers/organizations-post/doRestore");
const doAddRepresentative_1 = require("../handlers/organizations-post/doAddRepresentative");
const doUpdateRepresentative_1 = require("../handlers/organizations-post/doUpdateRepresentative");
const doDeleteRepresentative_1 = require("../handlers/organizations-post/doDeleteRepresentative");
const doSetDefaultRepresentative_1 = require("../handlers/organizations-post/doSetDefaultRepresentative");
const doGetRemarks_1 = require("../handlers/organizations-post/doGetRemarks");
const doGetRemark_1 = require("../handlers/organizations-post/doGetRemark");
const doAddRemark_1 = require("../handlers/organizations-post/doAddRemark");
const doEditRemark_1 = require("../handlers/organizations-post/doEditRemark");
const doDeleteRemark_1 = require("../handlers/organizations-post/doDeleteRemark");
const reminders_1 = require("../handlers/organizations-get/reminders");
const doGetReminders_1 = require("../handlers/organizations-post/doGetReminders");
const doGetReminder_1 = require("../handlers/organizations-post/doGetReminder");
const doAddReminder_1 = require("../handlers/organizations-post/doAddReminder");
const doEditReminder_1 = require("../handlers/organizations-post/doEditReminder");
const doDismissReminder_1 = require("../handlers/organizations-post/doDismissReminder");
const doDeleteReminder_1 = require("../handlers/organizations-post/doDeleteReminder");
const doGetBankRecords_1 = require("../handlers/organizations-post/doGetBankRecords");
const doAddBankRecord_1 = require("../handlers/organizations-post/doAddBankRecord");
const doEditBankRecord_1 = require("../handlers/organizations-post/doEditBankRecord");
const doUpdateBankRecordsByMonth_1 = require("../handlers/organizations-post/doUpdateBankRecordsByMonth");
const doDeleteBankRecord_1 = require("../handlers/organizations-post/doDeleteBankRecord");
const doGetBankRecordStats_1 = require("../handlers/organizations-post/doGetBankRecordStats");
const doRollForward_1 = require("../handlers/organizations-post/doRollForward");
const doGetInactive_1 = require("../handlers/organizations-post/doGetInactive");
const recovery_1 = require("../handlers/organizations-get/recovery");
const router = express_1.Router();
router.get("/", (_req, res) => {
    res.render("organization-search", {
        headTitle: "Organizations"
    });
});
router.post("/doSearch", doSearch_1.handler);
router.all("/doGetAll", doGetAll_1.handler);
router.get("/reminders", reminders_1.handler);
router.get("/cleanup", permissionHandlers.updateGetHandler, cleanup_1.handler);
router.post("/doGetInactive", permissionHandlers.updatePostHandler, doGetInactive_1.handler);
router.get("/recovery", permissionHandlers.adminGetHandler, recovery_1.handler);
router.post("/doGetRemarks", doGetRemarks_1.handler);
router.post("/doGetRemark", doGetRemark_1.handler);
router.post("/doAddRemark", permissionHandlers.createPostHandler, doAddRemark_1.handler);
router.post("/doEditRemark", permissionHandlers.createPostHandler, doEditRemark_1.handler);
router.post("/doDeleteRemark", permissionHandlers.createPostHandler, doDeleteRemark_1.handler);
router.post("/doGetReminders", doGetReminders_1.handler);
router.post("/doGetReminder", doGetReminder_1.handler);
router.post("/doAddReminder", permissionHandlers.createPostHandler, doAddReminder_1.handler);
router.post("/doEditReminder", permissionHandlers.createPostHandler, doEditReminder_1.handler);
router.post("/doDismissReminder", permissionHandlers.createPostHandler, doDismissReminder_1.handler);
router.post("/doDeleteReminder", permissionHandlers.createPostHandler, doDeleteReminder_1.handler);
router.post("/doGetBankRecords", doGetBankRecords_1.handler);
router.post("/doGetBankRecordStats", doGetBankRecordStats_1.handler);
router.post("/doAddBankRecord", permissionHandlers.createPostHandler, doAddBankRecord_1.handler);
router.post("/doEditBankRecord", permissionHandlers.createPostHandler, doEditBankRecord_1.handler);
router.post("/doUpdateBankRecordsByMonth", permissionHandlers.createPostHandler, doUpdateBankRecordsByMonth_1.handler);
router.post("/doDeleteBankRecord", permissionHandlers.createPostHandler, doDeleteBankRecord_1.handler);
router.get("/new", permissionHandlers.createGetHandler, new_1.handler);
router.post("/doSave", permissionHandlers.createPostHandler, doSave_1.handler);
router.post("/doDelete", permissionHandlers.createPostHandler, doDelete_1.handler);
router.post("/doRestore", permissionHandlers.updatePostHandler, doRestore_1.handler);
router.post("/doRollForward", permissionHandlers.createPostHandler, doRollForward_1.handler);
router.get("/:organizationID", view_1.handler);
router.get("/:organizationID/edit", permissionHandlers.createGetHandler, edit_1.handler);
router.post("/:organizationID/doAddOrganizationRepresentative", permissionHandlers.createPostHandler, doAddRepresentative_1.handler);
router.post("/:organizationID/doEditOrganizationRepresentative", permissionHandlers.createPostHandler, doUpdateRepresentative_1.handler);
router.post("/:organizationID/doDeleteOrganizationRepresentative", permissionHandlers.createPostHandler, doDeleteRepresentative_1.handler);
router.post("/:organizationID/doSetDefaultRepresentative", permissionHandlers.createPostHandler, doSetDefaultRepresentative_1.handler);
module.exports = router;
